### ISSUE TITLE
Rebuild forgebox package

### ISSUE THREAD

**Issue by sethstone** [andrew-dixon/cb-jwt#4]
Would it be possible to rebuild/reupload the forgebox package?  I'm including this library in my project via box.json but I have to apply the previous fix in #2 manually.

**Comment by andrew-dixon** [comment]
@sethstone I'll take a look at this over the weekend, just need to remember what to do 😄

**Comment by andrew-dixon** [comment]
@sethstone Actually I think I've done this, can you double check for me and confirm. Thanks.

**Comment by sethstone** [comment]
Looks good!
